# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: social_connect_dev
  pool: 5
  username: postgres
  password: nitanshu
test:
  adapter: postgresql
  encoding: unicode
  database: social_connect_test
  pool: 5
  username: postgres
  password: nitanshu


